### ISSUE TITLE
插件本身有问题

### ISSUE THREAD

**Issue by 2855754027** [irasutoya/chicken-dupe#2]
首先我用的服务端spigot 1.12.2 java:17
你的插件我已成功编译
你的插件已成功加载
出现以下3个问题:
1. 不能给鸡喂食小麦种子
2. 右键成年的鸡没有任何反应
3. 右键成年的鸡过后data.yum数据文件里面并没有存放这只鸡的数据
最后希望你能快点解决好吗？
谢谢了

**Comment by irasutoya** [comment]
请自行修改代码，谢谢配合。
